[build]
  base = "public" # Base directory where your project files are located
  command = "npm run build"
  publish = "public/dist" # Publish directory inside the base directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
